name: mobile_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.7
  record: ^5.0.5
  path_provider: ^2.1.5
  just_audio: ^0.9.39

dependency_overrides:
  record_linux: ^1.2.1
  record_platform_interface: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
