name: mobile_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.12
  pdf: ^3.11.3
  printing: ^5.14.2
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  fl_chart: ^0.65.0
  mailer: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
