name: mobile_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  fl_chart: ^0.65.0
  mailer: ^6.1.0
  firebase_storage: ^13.0.1
  record: ^5.0.5
  path_provider: ^2.1.5
  just_audio: ^0.9.39
  flutter_local_notifications: ^19.4.1
  firebase_messaging: ^16.0.1
  shared_preferences: ^2.2.3

dependency_overrides:
  record_linux: ^1.2.1
  record_platform_interface: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
