// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBiCVqZW_UVGLan6a1i_b3FSoWTkAFDhk',
    appId: '1:815737998035:web:7ce105a111e85a0dea2226',
    messagingSenderId: '815737998035',
    projectId: 'mobile-application-6c51f',
    authDomain: 'mobile-application-6c51f.firebaseapp.com',
    storageBucket: 'mobile-application-6c51f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlr230PBK6tLYIsuGcSFZmU_vQ93UJoFc',
    appId: '1:815737998035:android:7e4183a11fce6ae7ea2226',
    messagingSenderId: '815737998035',
    projectId: 'mobile-application-6c51f',
    storageBucket: 'mobile-application-6c51f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzALBHoJjSujlSAVbVwR7G8cPtYClyy6g',
    appId: '1:815737998035:ios:c068c458b787cec9ea2226',
    messagingSenderId: '815737998035',
    projectId: 'mobile-application-6c51f',
    storageBucket: 'mobile-application-6c51f.firebasestorage.app',
    iosBundleId: 'com.example.mobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzALBHoJjSujlSAVbVwR7G8cPtYClyy6g',
    appId: '1:815737998035:ios:c068c458b787cec9ea2226',
    messagingSenderId: '815737998035',
    projectId: 'mobile-application-6c51f',
    storageBucket: 'mobile-application-6c51f.firebasestorage.app',
    iosBundleId: 'com.example.mobileApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBiCVqZW_UVGLan6a1i_b3FSoWTkAFDhk',
    appId: '1:815737998035:web:64e367cbd5360e1cea2226',
    messagingSenderId: '815737998035',
    projectId: 'mobile-application-6c51f',
    authDomain: 'mobile-application-6c51f.firebaseapp.com',
    storageBucket: 'mobile-application-6c51f.firebasestorage.app',
  );
}
